language: ruby
rvm:
  - 2.2.3
env:
  - DEVISE_SECRET_KEY=1234 DEVISE_MAIL_SENDER=test@localhost VHOST=localhost VHOST_PROTOCOL=http FROM_EMAIL=root@localhost SECRET_KEY_BASE=4321
script:
  - bundle exec rake db:setup
  - bundle exec rake
after_failure: "cat log/test.log"
